### ISSUE TITLE
No picture on iOS

### ISSUE THREAD

**Issue by jeirix** [marianpekar/ue5-fetch-art#1]
Hello Marian,

first of all many thanks for this repo it's really awesome, I successfully tested and re-tested both in win/mac os x, and it definitively works like a charm.
Unfortunately I couldn't make it work on iOS, the app launch perfectly the text is correctly visible however no way to display the picture. Did you ever experienced this? Any idea of why the rendering isn't working on iOS?

Many thanks.
J

**Comment by marianpekar** [comment]
Hi jeirix, I don't own any iPhone to replicate the issue on, and tbh I haven't tested on Android device either. I generally don't see UE as a good fit to build mobile games with atm or in a near future. Unity might be a better option for mobile development.
